name: OWASP ZAP Full Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap_full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ZAP full scan
        uses: zaproxy/action-full-scan@v0.8.0-beta
        with:
          docker_name: 'zaproxy/zap-stable'
          target: 'http://localhost:7860'
        continue-on-error: true

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-report
          path: |
            report_html.html
            report_md.md
            report_json.json
